"""initial schema

Revision ID: 932dfd9038e9
Revises: 
Create Date: 2026-03-11 11:33:32.815808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '932dfd9038e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_clusters',
    sa.Column('canonical_title', sa.Text(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'MONITORING', 'RESOLVED', 'SUPPRESSED', name='event_status_enum'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('trusted_source_count', sa.Integer(), nullable=False),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latest_severity_score', sa.Float(), nullable=True),
    sa.Column('latest_confidence_score', sa.Float(), nullable=True),
    sa.Column('latest_summary', sa.Text(), nullable=True),
    sa.Column('last_alert_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='event_last_alert_level_enum'), nullable=True),
    sa.Column('last_alert_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_clusters_first_seen_at', 'event_clusters', ['first_seen_at'], unique=False)
    op.create_index('ix_event_clusters_last_seen_at', 'event_clusters', ['last_seen_at'], unique=False)
    op.create_index('ix_event_clusters_status', 'event_clusters', ['status'], unique=False)
    op.create_index('ix_event_clusters_topic_region', 'event_clusters', ['topic', 'region'], unique=False)
    op.create_table('sources',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.Enum('RSS', 'API', 'WEBSITE', 'SOCIAL', 'GOVERNMENT', 'OTHER', name='source_type_enum'), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('rss_url', sa.Text(), nullable=True),
    sa.Column('api_url', sa.Text(), nullable=True),
    sa.Column('trust_tier', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'VERIFIED', name='trust_tier_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('polling_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('alerts',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('alert_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alert_level_enum'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('analysis_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event_clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_alert_level', 'alerts', ['alert_level'], unique=False)
    op.create_index('ix_alerts_created_at', 'alerts', ['created_at'], unique=False)
    op.create_index('ix_alerts_event_id', 'alerts', ['event_id'], unique=False)
    op.create_table('analyses',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('severity_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('reasoning_brief', sa.Text(), nullable=True),
    sa.Column('key_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event_clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analyses_created_at', 'analyses', ['created_at'], unique=False)
    op.create_index('ix_analyses_event_id', 'analyses', ['event_id'], unique=False)
    op.create_index('ix_analyses_model_name', 'analyses', ['model_name'], unique=False)
    op.create_table('articles',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('summary_hint', sa.Text(), nullable=True),
    sa.Column('raw_payload_path', sa.Text(), nullable=True),
    sa.Column('raw_html_path', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('normalized_hash', sa.String(length=128), nullable=True),
    sa.Column('region_hint', sa.String(length=100), nullable=True),
    sa.Column('topic_hint', sa.String(length=100), nullable=True),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('INGESTED', 'NORMALIZED', 'CLUSTERED', 'ANALYZED', 'REJECTED', name='article_status_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event_clusters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_articles_source_external_id')
    )
    op.create_index('ix_articles_event_id', 'articles', ['event_id'], unique=False)
    op.create_index('ix_articles_fetched_at', 'articles', ['fetched_at'], unique=False)
    op.create_index('ix_articles_normalized_hash', 'articles', ['normalized_hash'], unique=False)
    op.create_index('ix_articles_published_at', 'articles', ['published_at'], unique=False)
    op.create_index('ix_articles_status', 'articles', ['status'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('min_severity', sa.Float(), nullable=False),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('regions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('telegram_enabled', sa.Boolean(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(), nullable=True),
    sa.Column('whatsapp_enabled', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_phone', sa.String(), nullable=True),
    sa.Column('messenger_enabled', sa.Boolean(), nullable=False),
    sa.Column('messenger_psid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('deliveries',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('TELEGRAM', 'WHATSAPP', 'MESSENGER', name='delivery_channel_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RETRYING', 'SENT', 'FAILED', 'SKIPPED', name='delivery_status_enum'), nullable=False),
    sa.Column('destination', sa.Text(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deliveries_alert_id', 'deliveries', ['alert_id'], unique=False)
    op.create_index('ix_deliveries_channel', 'deliveries', ['channel'], unique=False)
    op.create_index('ix_deliveries_created_at', 'deliveries', ['created_at'], unique=False)
    op.create_index('ix_deliveries_status', 'deliveries', ['status'], unique=False)
    op.create_table('event_articles',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['event_clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'article_id'),
    sa.UniqueConstraint('event_id', 'article_id', name='uq_event_articles_event_article')
    )
    op.create_index('ix_event_articles_article_id', 'event_articles', ['article_id'], unique=False)
    op.create_index('ix_event_articles_event_id', 'event_articles', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_articles_event_id', table_name='event_articles')
    op.drop_index('ix_event_articles_article_id', table_name='event_articles')
    op.drop_table('event_articles')
    op.drop_index('ix_deliveries_status', table_name='deliveries')
    op.drop_index('ix_deliveries_created_at', table_name='deliveries')
    op.drop_index('ix_deliveries_channel', table_name='deliveries')
    op.drop_index('ix_deliveries_alert_id', table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_table('user_preferences')
    op.drop_index('ix_articles_status', table_name='articles')
    op.drop_index('ix_articles_published_at', table_name='articles')
    op.drop_index('ix_articles_normalized_hash', table_name='articles')
    op.drop_index('ix_articles_fetched_at', table_name='articles')
    op.drop_index('ix_articles_event_id', table_name='articles')
    op.drop_table('articles')
    op.drop_index('ix_analyses_model_name', table_name='analyses')
    op.drop_index('ix_analyses_event_id', table_name='analyses')
    op.drop_index('ix_analyses_created_at', table_name='analyses')
    op.drop_table('analyses')
    op.drop_index('ix_alerts_event_id', table_name='alerts')
    op.drop_index('ix_alerts_created_at', table_name='alerts')
    op.drop_index('ix_alerts_alert_level', table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('users')
    op.drop_table('sources')
    op.drop_index('ix_event_clusters_topic_region', table_name='event_clusters')
    op.drop_index('ix_event_clusters_status', table_name='event_clusters')
    op.drop_index('ix_event_clusters_last_seen_at', table_name='event_clusters')
    op.drop_index('ix_event_clusters_first_seen_at', table_name='event_clusters')
    op.drop_table('event_clusters')
    # ### end Alembic commands ###
